<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <div class="img"></div>

    <script>
        const images = [
            {name: "a", url: "http://placeimg.com/640/480/animals"},
            {name: "b", url: "http://placeimg.com/640/480/arch"},
            {name: "c", url: "http://placeimg.com/640/480/nature"},
            {name: "d", url: "http://placeimg.com/640/480/people"},
        ]


        const images2 = [
            {name: "a", url: "http://placeimg.com/640/480/animals"},
            {name: "b", url: "http://placeimg.co"},
            {name: "c", url: "http://placeimg.com/640/480/nature"},
            {name: "d", url: "http://placeimg.com/640/480/people"},
        ]


        //인동님 비동기 에러 핸들링 
        // 

        // 1번 에러 소스 (images2를 돌면서 2번이미지에서 에러가 났지만 3번 4번 요청은 계속 실행됨)
        async function f1() {
            try {
                const total = await images2
                .map(async ({ url }) => {
                    try {
                        const img = await loadImage(url)
                        // console.log('?', img)
                        return img.height;
                    } catch(e) {
                        console.error(e)
                        throw e;
                    }
                })
                // .map(img => img.height)
                // .forEach(async (a) => { console.log(await a) })
                .reduce(async (total, height) => await total + await height, 0)

                console.log(total)
            } catch(e) {
                console.error(0)
            }
        }
        // f1();








        function loadImage(url) {
            return new Promise((resolve, reject) => {
                let img = new Image();
                img.src = url;
                console.log('이미지 로드', url) 
                //1번 에러소스에서 2번쨰 이미지를 불러오진 않았지만 이미지 로드가 모두 일어남.
                //이게 요청일때는 상관없지만 업데이트같은 경우 크게 문제가 생김..에러 핸들링은 했지만 버그가 있는 코드.
                img.onload = function() {
                    resolve(img)
                }
                img.onerror = function(e) {
                    // 에러는 에러를 발생시켜야 에러를 잡을 수 있음
                    reject(e)
                }
                return img;
            })
        }

        // console.log( loadImage(images[0].url) )




        // 제네레이터로 추상화
        function* mapi(fn, iter) {
            for(const a of iter) {
                yield a instanceof Promise ? a.then(fn) : fn(a); // 비동기면 댄에 합성 동기면 그냥 리턴
            }
        }


        // async function f2() {
        //     let acc = 0;
        //     for await (const a of mapi(img => img.height, mapi(({ url }) => loadImage(url), images))) {
        //         console.log(a) //각 480씩 
        //         acc = acc + a
        //     }
        //     console.log(acc) //1920 잘찍힘
        // }
        // f2();

        // 위 f2함수는 결국 리듀서 함수임. 아래 리팩토링
        async function reduceAsync(fn, acc, iter) {
            for await (const a of iter) {
                acc = fn(acc, a)
            }
            return acc 
        }
        
        // 와우...
        async function f2() {
          try {
            return await reduceAsync( (a, b) => a + b, 0, mapi(img => img.height, mapi(({ url }) => loadImage(url), images) ))
          } catch(e) {
            console.log('server error', e)
            return 0
          }
        }
        // f2().then(total => console.log(total));






        // ########### 위보다 더 좋은 코드...에러핸들링을 하지않는 코드
        // 1. 함수 내의 값 외부값을 바로 참조하는게 아닌 인자로 제한하는 것...
        // 2. async await 없앨 수 있고 즉시 리턴이기 때문에 표현식과 애로함수로 간결해짐
        // 3. f3 함수에서 에러핸들링을 하면 안되고 ..(어떤 값이 올지 모르기 떄문에 )
        // 4. imags를 보내는 개발자가 에러핸들링을 해서 보내는게 맞음 
        // 5. f3 함수에서는 에러가 터질 수 있게만 작성해주면 됨 

        const f3 = imgs => reduceAsync( (a, b) => a + b, 0, mapi(img => img.height, mapi(({ url }) => loadImage(url), imgs) ))
        
        f3(images).catch(_ => 0).then(total => console.log(total));
        f3(images2).catch(_ => 0).then(total => console.log(total));




/* 
    # 인동님 정리
    https://www.youtube.com/watch?v=o9JnT4sneAQ

    1. Promise, async/await, try/catch 를 정확히 다루는 것이 중요

    2. 제네레이터/이터레이터/이터러블을 잘 응용하면 코드의 표현력을 
       더할 뿐 아니라 에러핸들링도 더 잘됨

    3. 순수함수에서는 에러가 발생되도록 그냥 두는 것이 더 좋다

    4. 에러 핸들링 코드는 부수효과를 일으킬 코드 주변에 작성하는 것이 좋음

    5. 불필요하게 에러 핸들링을 미리 해두는 것은 에러를 숨길 뿐

    6. 차라리 에러를 발생시키는 게 좋음. sentry.io같은 서비스를 이용하여 
       발생되는 모든 에러를 볼 수 있도록 하는 것이 고객과 
       회사를 위하는 더 좋은 해법 




*/
























        // let hoho = images.map(( { url } ) => {
        //     return new Promise((res, rej) => {
        //         // console.log(url)
        //         let img = new Image()
        //         img.src = url
        //         img.onload = function() {
        //             res(img)
        //         }
        //     })
        //     return img
        // })

        // const ele = document.querySelector('.img')
        // let re = null;
        // hoho.map(item => {
        //     // console.log(item)
        //     async function redu() {
        //         const hoho = await item;
        //         re += hoho.height
        //         // console.log('asdasd',hoho.height) 
        //     }
        //     redu();

        //     console.log(re)

        //     item.then(img => {
        //         console.log(img.height)
        //         ele.appendChild(img)
        //     })
        // })
        // hoho[0].then(img => {
        //     console.log('?', img)
        // })




        
    </script>
</body>
</html>